#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail
#--cap-add SYS_TTY_CONFIG --device /dev/input --device /dev/dri --device $(tty)
xhost +
docker run "$@" -it --net=host -v  /tmp/.X11-unix:/tmp/.X11-unix \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v /run/udev/data:/run/udev/data \
 -v $PWD/minecROS_ws:/home/ubuntu/minecROS_ws \
 --ipc=host \
 --shm-size=8G \
 -e DISPLAY=$DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all --privileged minecros:latest /bin/bash
